# syntax=docker/dockerfile:1
FROM python:slim
WORKDIR /
COPY /flaskr/requirements.txt /flaskr/requirements.txt

RUN pip install --upgrade pip
RUN pip install -r /flaskr/requirements.txt
COPY /flaskr /flaskr
COPY /data /data

ENV FLASK_APP=flaskr

EXPOSE 5001


COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]