services:
  flaskr:
    container_name: dis-flaskr
    build:
      context: .
      dockerfile: Dockerfile.flaskr
    ports:
      - 5001:5001  
    depends_on:
      db:
        condition: service_healthy    
    links: 
        - db # This links to the above defined 'db'
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5123:5432
    env_file:
      - .db.env    
    volumes:
      - ./pData:/var/lib/postgresql/data
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
  client:
    container_name: dis-client
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:5173
    # command: ["flask", "init-db"]